from snakemake.utils import update_config

include: "params/default.settings"

include: "read_filtering/Snakefile"
include: "taxonomic_classification/Snakefile"
include: "assembly/Snakefile"
include: "comparison/Snakefile"
